<?php
if ( ! defined( 'ABSPATH' ) ) exit;
class NHK_Form_Public {
 const ACTION='nhk_form_submit';
 public static function register(){add_shortcode('nhk_form',array(__CLASS__,'shortcode'));add_action('admin_post_nopriv_'.self::ACTION,array(__CLASS__,'submit'));add_action('admin_post_'.self::ACTION,array(__CLASS__,'submit'));}
 public static function shortcode($a){$a=shortcode_atts(array('id'=>0),$a);$id=absint($a['id']);if(NHK_Form_Post_Type::SLUG!==get_post_type($id)||'publish'!==get_post_status($id))return '';ob_start();$error=sanitize_key($_GET['nhk_form_error']??'');$ok=!empty($_GET['nhk_form_submitted']);if($ok){echo '<div class="nhk-form-success">'.wp_kses_post(nl2br(NHK_Form_Post_Type::success($id))).'</div>';return ob_get_clean();}?>
 <form method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="nhk-form"><?php if(NHK_Form_Post_Type::description($id)):?><div class="nhk-form-description"><?php echo wpautop(wp_kses_post(NHK_Form_Post_Type::description($id)));?></div><?php endif;?><?php if($error):?><div class="nhk-form-error">入力内容を確認して、もう一度送信してください。</div><?php endif;?>
 <input type="hidden" name="action" value="<?php echo self::ACTION;?>"><input type="hidden" name="form_id" value="<?php echo $id;?>"><input type="text" name="nhk_form_website" value="" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px"><?php wp_nonce_field(self::ACTION.':'.$id,'nhk_form_nonce');?>
 <div class="nhk-form-fields" style="display:flex;flex-wrap:wrap;gap:16px"><?php foreach(NHK_Form_Post_Type::fields($id) as $f):self::render_field($f);endforeach;?></div><p><button type="submit">送信する</button></p></form><?php return ob_get_clean();}
 private static function render_field($f){$type=$f['type']??'text';$key=$f['key'];$name='nhk_field['.$key.']';$file='nhk_file['.$key.']';$w=max(10,min(100,absint($f['width']??100)));$req=!empty($f['required']);$opts=array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)($f['options']??''))));?><div class="nhk-form-field" style="width:<?php echo $w;?>%;box-sizing:border-box"><label><?php if($type!=='checkbox')echo esc_html($f['label']);?><?php if($req)echo ' *';?><br><?php if($type==='textarea'):?><textarea name="<?php echo esc_attr($name);?>" placeholder="<?php echo esc_attr($f['placeholder']??'');?>" <?php echo $req?'required':'';?>></textarea><?php elseif($type==='select'):?><select name="<?php echo esc_attr($name);?>" <?php echo $req?'required':'';?>><option value="">選択してください</option><?php foreach($opts as $o):?><option value="<?php echo esc_attr($o);?>"><?php echo esc_html($o);?></option><?php endforeach;?></select><?php elseif($type==='radio'):foreach($opts as $n=>$o):?><label><input type="radio" name="<?php echo esc_attr($name);?>" value="<?php echo esc_attr($o);?>" <?php echo $req&&$n===0?'required':'';?>> <?php echo esc_html($o);?></label><br><?php endforeach;?><?php elseif($type==='checkbox'):?><label><input type="checkbox" name="<?php echo esc_attr($name);?>" value="1" <?php echo $req?'required':'';?>> <?php echo esc_html($f['label']);?></label><?php elseif($type==='file'):$accept=self::accept($f);?><input type="file" name="<?php echo esc_attr($file);?>" <?php echo $accept?'accept="'.esc_attr($accept).'"':'';?> <?php echo $req?'required':'';?>><?php else:?><input type="<?php echo esc_attr(in_array($type,array('email','tel','number','date'),true)?$type:'text');?>" name="<?php echo esc_attr($name);?>" placeholder="<?php echo esc_attr($f['placeholder']??'');?>"<?php echo self::length_attrs($f);?> <?php echo $req?'required':'';?>><?php endif;?></label><?php if(!empty($f['help_text'])):?><div class="nhk-form-help"><?php echo esc_html($f['help_text']);?></div><?php endif;?></div><?php if(!empty($f['row_end'])): ?><div style="flex-basis:100%;height:0"></div><?php endif; ?><?php }
 public static function submit(){$id=absint($_POST['form_id']??0);$redirect=$id?get_permalink($id):home_url('/');if(!$id||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nhk_form_nonce']??'')),self::ACTION.':'.$id))self::redirect($redirect,'security');if(!empty($_POST['nhk_form_website']))self::redirect($redirect,'invalid');$input=is_array($_POST['nhk_field']??null)?wp_unslash($_POST['nhk_field']):array();$values=array();$uploads=array();$attachments=array();
 foreach(NHK_Form_Post_Type::fields($id) as $f){$key=$f['key'];$type=$f['type'];if($type==='file'){$u=self::upload($key,$f);if(is_wp_error($u)){if($f['required']||$u->get_error_code()!=='empty')self::redirect($redirect,'file');continue;}$uploads[$key]=$u;$attachments[]=$u['file'];$values[$key]=basename($u['file']);continue;}$raw=$input[$key]??'';if(is_array($raw))self::redirect($redirect,'validation');$raw=trim((string)$raw);if($f['required']&&$raw==='')self::redirect($redirect,'required');if($raw!==''){if(!self::validate($raw,$f))self::redirect($redirect,'validation');}$values[$key]=self::sanitize($raw,$type);}
 if(NHK_Form_Post_Type::mode($id)==='post_submission'){$schema=NHK_Form_Schema_Registry::get(NHK_Form_Post_Type::schema($id));if(!$schema)self::redirect($redirect,'schema');$map=$schema['map'];$new=wp_insert_post(array('post_type'=>$schema['post_type'],'post_status'=>'draft','post_title'=>sanitize_text_field($values[$map['title']]??get_the_title($id)),'post_content'=>wp_kses_post($values[$map['content']]??'')),true);if(is_wp_error($new))self::redirect($redirect,'draft');foreach(($map['meta']??array()) as $meta=>$key)update_post_meta($new,$meta,$values[$key]??'');foreach($uploads as $key=>$u){$aid=self::attach($u,$new);$filemap=$map['files'][$key]??'';if($filemap==='featured')set_post_thumbnail($new,$aid);elseif($filemap)update_post_meta($new,$filemap,$aid);}do_action('nhk_form_created_post',$new,$id,$values,$schema);}
 self::notify($id,$values,$attachments);self::auto_reply($id,$values);wp_safe_redirect(add_query_arg('nhk_form_submitted','1',$redirect));exit;}
 private static function notify($id,$values,$attachments){$to=NHK_Form_Post_Type::recipients($id);if(!$to)return;$lines=array(get_the_title($id),'', '送信日時: '.current_time('Y-m-d H:i:s'));foreach(NHK_Form_Post_Type::fields($id) as $f)$lines[]=$f['label'].': '.($values[$f['key']]??'');$headers=array('Content-Type: text/plain; charset=UTF-8');$from=NHK_Form_Post_Type::from_email($id);$name=NHK_Form_Post_Type::from_name($id);if($from)$headers[]=$name?'From: '.$name.' <'.$from.'>':'From: '.$from;$reply=self::reply_to($id,$values);if($reply)$headers[]='Reply-To: '.$reply;wp_mail($to,NHK_Form_Post_Type::mail_subject($id),implode("\n",$lines),$headers,$attachments);}
 private static function auto_reply($id,$values){if(!NHK_Form_Post_Type::auto_reply($id))return;foreach(NHK_Form_Post_Type::fields($id) as $f)if(($f['type']??'')==='email'&&!empty($values[$f['key']])&&is_email($values[$f['key']])){wp_mail($values[$f['key']],NHK_Form_Post_Type::mail_subject($id),NHK_Form_Post_Type::success($id),array('Content-Type: text/plain; charset=UTF-8'));break;}}
 private static function reply_to($id,$v){$m=NHK_Form_Post_Type::reply_mode($id);if($m==='fixed')return NHK_Form_Post_Type::reply_email($id);if($m==='form_field'){$x=sanitize_email($v[NHK_Form_Post_Type::reply_field($id)]??'');return is_email($x)?$x:'';}return '';}
 private static function validate($v,$f){$t=$f['type'];$min=absint($f['min_length']??0);$max=absint($f['max_length']??0);$len=function_exists('mb_strlen')?mb_strlen($v):strlen($v);if(($min&&$len<$min)||($max&&$len>$max))return false;if($t==='email'&&!is_email($v))return false;if($t==='number'&&!is_numeric($v))return false;if($t==='date'){ $d=DateTime::createFromFormat('Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)return false;}if(in_array($t,array('select','radio'),true)&&!in_array($v,array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)($f['options']??'')))),true))return false;return true;}
 private static function sanitize($v,$t){if($t==='textarea')return sanitize_textarea_field($v);if($t==='email')return sanitize_email($v);if($t==='checkbox')return $v==='1'?'1':'';return sanitize_text_field($v);}
 private static function upload($key,$f){if(empty($_FILES['nhk_file']['name'][$key]))return new WP_Error('empty','empty');$file=array('name'=>$_FILES['nhk_file']['name'][$key],'type'=>$_FILES['nhk_file']['type'][$key],'tmp_name'=>$_FILES['nhk_file']['tmp_name'][$key],'error'=>(int)$_FILES['nhk_file']['error'][$key],'size'=>(int)$_FILES['nhk_file']['size'][$key]);if($file['error']!==UPLOAD_ERR_OK||!is_uploaded_file($file['tmp_name']))return new WP_Error('upload','upload');$ext=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION));$allowed=self::extensions($f);if(!$allowed||!in_array($ext,$allowed,true)||$file['size']>max(1,absint($f['max_file_size_mb']??5))*1024*1024)return new WP_Error('file','file');require_once ABSPATH.'wp-admin/includes/file.php';$mimes=array();foreach(wp_get_mime_types() as $pat=>$mime)foreach(explode('|',$pat) as $e)if(in_array(strtolower($e),$allowed,true))$mimes[$pat]=$mime;$r=wp_handle_upload($file,array('test_form'=>false,'mimes'=>$mimes));return isset($r['error'])?new WP_Error('upload',$r['error']):$r;}
 private static function attach($u,$post){$type=wp_check_filetype(basename($u['file']),null);$aid=wp_insert_attachment(array('post_mime_type'=>$type['type']??'','post_title'=>sanitize_file_name(pathinfo($u['file'],PATHINFO_FILENAME)),'post_status'=>'inherit'),$u['file'],$post);if($aid&&!is_wp_error($aid)){require_once ABSPATH.'wp-admin/includes/image.php';wp_update_attachment_metadata($aid,wp_generate_attachment_metadata($aid,$u['file']));}return is_wp_error($aid)?0:$aid;}
 private static function extensions($f){return array_values(array_unique(array_filter(array_map(function($x){return preg_replace('/[^a-z0-9]/','',$x);},preg_split('/[\s,]+/',strtolower((string)($f['allowed_extensions']??'')))))));}
 private static function accept($f){$x=self::extensions($f);return $x?implode(',',array_map(function($v){return '.'.$v;},$x)):'';}
 private static function length_attrs($f){$s='';if(!empty($f['min_length']))$s.=' minlength="'.absint($f['min_length']).'"';if(!empty($f['max_length']))$s.=' maxlength="'.absint($f['max_length']).'"';return $s;}
 private static function redirect($url,$error){wp_safe_redirect(add_query_arg('nhk_form_error',sanitize_key($error),$url));exit;}
}