<?php
if ( ! defined( 'ABSPATH' ) ) exit;
class NHK_Form_Admin {
 const NONCE='nhk_form_meta_nonce';
 public static function register(){add_action('add_meta_boxes',array(__CLASS__,'meta_box'));add_action('save_post_'.NHK_Form_Post_Type::SLUG,array(__CLASS__,'save'),10,2);}
 public static function meta_box(){add_meta_box('nhk-form-settings','フォーム設定',array(__CLASS__,'render'),NHK_Form_Post_Type::SLUG,'normal','high');}
 public static function render($post){
  wp_nonce_field(self::NONCE,self::NONCE);$mode=NHK_Form_Post_Type::mode($post->ID);$schema=NHK_Form_Post_Type::schema($post->ID);$fields=NHK_Form_Post_Type::fields($post->ID);$schemas=NHK_Form_Schema_Registry::all();
  ?><style>.nhk-field{border:1px solid #ccd0d4;padding:14px;margin:12px 0;background:#fff}.nhk-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.nhk-grid label{display:block;font-weight:600}.nhk-grid input,.nhk-grid select{width:100%}@media(max-width:782px){.nhk-grid{grid-template-columns:1fr}}</style>
  <h3>フォームの用途</h3>
  <label><input type="radio" name="nhk_form_mode" value="standard" <?php checked($mode,'standard');?>> 通常フォーム（通知・受付）</label><br>
  <label><input type="radio" name="nhk_form_mode" value="post_submission" <?php checked($mode,'post_submission');?>> 投稿作成フォーム（送信内容から下書きを作成）</label>
  <p class="nhk-schema-wrap"><label><strong>投稿スキーマ</strong><br><select name="nhk_form_schema" id="nhk_form_schema"><option value="">選択してください</option><?php foreach($schemas as $key=>$item):?><option value="<?php echo esc_attr($key);?>" <?php selected($schema,$key);?>><?php echo esc_html($item['label']);?></option><?php endforeach;?></select></label>
  <button type="button" class="button" id="nhk-apply-schema">スキーマから項目を生成</button> <span class="description">連携プラグインが提供する入力定義からフォーム項目を自動生成します。</span></p>
  <p><label><strong>説明文</strong><br><textarea class="large-text" rows="3" name="nhk_form_description"><?php echo esc_textarea(NHK_Form_Post_Type::description($post->ID));?></textarea></label></p>
  <hr><h3>メール通知設定</h3><div class="nhk-grid">
  <p><label>通知先メールアドレス（複数可）<textarea class="large-text" rows="3" name="nhk_form_recipients"><?php echo esc_textarea(implode("\n",NHK_Form_Post_Type::recipients($post->ID)));?></textarea></label><span class="description">改行またはカンマ区切り。</span></p>
  <p><label>メール件名<input type="text" name="nhk_form_mail_subject" value="<?php echo esc_attr(NHK_Form_Post_Type::mail_subject($post->ID));?>"></label></p>
  <p><label>差出人名<input type="text" name="nhk_form_from_name" value="<?php echo esc_attr(NHK_Form_Post_Type::from_name($post->ID));?>"></label></p>
  <p><label>差出人メールアドレス<input type="email" name="nhk_form_from_email" value="<?php echo esc_attr(NHK_Form_Post_Type::from_email($post->ID));?>"></label></p></div>
  <p><strong>返信先メールアドレス</strong><br><label><input type="radio" name="nhk_form_reply_to_mode" value="none" <?php checked(NHK_Form_Post_Type::reply_mode($post->ID),'none');?>> 指定しない</label><br><label><input type="radio" name="nhk_form_reply_to_mode" value="fixed" <?php checked(NHK_Form_Post_Type::reply_mode($post->ID),'fixed');?>> 固定メールアドレス</label> <input type="email" name="nhk_form_reply_to_email" value="<?php echo esc_attr(NHK_Form_Post_Type::reply_email($post->ID));?>"><br><label><input type="radio" name="nhk_form_reply_to_mode" value="form_field" <?php checked(NHK_Form_Post_Type::reply_mode($post->ID),'form_field');?>> フォーム項目を使用</label> <select name="nhk_form_reply_to_field"><option value="">メール項目を選択</option><?php foreach($fields as $f)if(($f['type']??'')==='email'):?><option value="<?php echo esc_attr($f['key']);?>" <?php selected(NHK_Form_Post_Type::reply_field($post->ID),$f['key']);?>><?php echo esc_html($f['label']);?></option><?php endif;?></select></p>
  <p><label>送信完了メッセージ<br><textarea class="large-text" rows="3" name="nhk_form_success"><?php echo esc_textarea(NHK_Form_Post_Type::success($post->ID));?></textarea></label></p>
  <p><label><input type="checkbox" name="nhk_form_auto_reply" value="1" <?php checked(NHK_Form_Post_Type::auto_reply($post->ID));?>> メールアドレス入力者へ自動返信を送る</label></p>
  <hr><h3>入力項目</h3><p class="description">追加・削除・上下移動で表示順を設定できます。</p><div id="nhk-fields"><?php foreach($fields as $i=>$f)self::field($i,$f);?></div><p><button type="button" class="button" id="nhk-add-field">項目を追加</button></p><template id="nhk-field-template"><?php self::field('__INDEX__',array());?></template>
  <script>(function(){const wrap=document.getElementById('nhk-fields'),tpl=document.getElementById('nhk-field-template');document.getElementById('nhk-add-field').onclick=()=>wrap.insertAdjacentHTML('beforeend',tpl.innerHTML.replace(/__INDEX__/g,Date.now()));wrap.addEventListener('click',e=>{const r=e.target.closest('.nhk-field');if(!r)return;if(e.target.classList.contains('nhk-remove'))r.remove();if(e.target.classList.contains('nhk-up')&&r.previousElementSibling)wrap.insertBefore(r,r.previousElementSibling);if(e.target.classList.contains('nhk-down')&&r.nextElementSibling)wrap.insertBefore(r.nextElementSibling,r);});const schemas=<?php echo wp_json_encode(array_map(function($s){return $s['fields'];},$schemas));?>;document.getElementById('nhk-apply-schema').onclick=()=>{const key=document.getElementById('nhk_form_schema').value;if(!schemas[key])return;wrap.innerHTML='';schemas[key].forEach((f,n)=>{let d=document.createElement('div');d.innerHTML=tpl.innerHTML.replace(/__INDEX__/g,'s_'+Date.now()+'_'+n);let r=d.firstElementChild;r.querySelector('[name$="[label]"]').value=f.label||'';r.querySelector('[name$="[key]"]').value=f.key||'';r.querySelector('[name$="[type]"]').value=f.type||'text';r.querySelector('[name$="[required]"]').checked=!!f.required;wrap.appendChild(r);});};})();</script><?php
 }
 private static function field($i,$f){$f=wp_parse_args($f,array('id'=>'','key'=>'','label'=>'','type'=>'text','required'=>false,'help_text'=>'','placeholder'=>'','options'=>'','min_length'=>0,'max_length'=>0,'width'=>'100','row_end'=>true,'allowed_extensions'=>'pdf,doc,docx,xls,xlsx,jpg,jpeg,png','max_file_size_mb'=>5));$types=array('text'=>'1行テキスト','email'=>'メールアドレス','tel'=>'電話番号','number'=>'数値','date'=>'年月日（カレンダー）','textarea'=>'複数行テキスト','select'=>'セレクトボックス','radio'=>'ラジオボタン','checkbox'=>'チェックボックス','file'=>'ファイル添付');?>
 <div class="nhk-field"><div class="nhk-grid"><p><label>項目ラベル<input name="nhk_form_fields[<?php echo esc_attr($i);?>][label]" value="<?php echo esc_attr($f['label']);?>"></label></p><p><label>項目キー<input name="nhk_form_fields[<?php echo esc_attr($i);?>][key]" value="<?php echo esc_attr($f['key']);?>"></label></p><p><label>項目種別<select name="nhk_form_fields[<?php echo esc_attr($i);?>][type]"><?php foreach($types as $k=>$v):?><option value="<?php echo esc_attr($k);?>" <?php selected($f['type'],$k);?>><?php echo esc_html($v);?></option><?php endforeach;?></select></label></p><p><label>プレースホルダー<input name="nhk_form_fields[<?php echo esc_attr($i);?>][placeholder]" value="<?php echo esc_attr($f['placeholder']);?>"></label></p><p><label>最小文字数<input type="number" min="0" name="nhk_form_fields[<?php echo esc_attr($i);?>][min_length]" value="<?php echo esc_attr((int)$f['min_length']);?>"></label></p><p><label>最大文字数<input type="number" min="0" name="nhk_form_fields[<?php echo esc_attr($i);?>][max_length]" value="<?php echo esc_attr((int)$f['max_length']);?>"></label></p><p><label>フィールド幅<select name="nhk_form_fields[<?php echo esc_attr($i);?>][width]"><?php foreach(array('10'=>'10%','25'=>'25%','33'=>'33%','50'=>'50%','66'=>'66%','75'=>'75%','100'=>'100%') as $k=>$v):?><option value="<?php echo $k;?>" <?php selected((string)$f['width'],(string)$k);?>><?php echo $v;?></option><?php endforeach;?></select></label></p></div>
 <p><label>補足説明<input class="widefat" name="nhk_form_fields[<?php echo esc_attr($i);?>][help_text]" value="<?php echo esc_attr($f['help_text']);?>"></label></p><p><label>選択肢（1行に1件）<textarea rows="3" class="widefat" name="nhk_form_fields[<?php echo esc_attr($i);?>][options]"><?php echo esc_textarea($f['options']);?></textarea></label></p><div class="nhk-grid"><p><label>許可するファイル形式<input name="nhk_form_fields[<?php echo esc_attr($i);?>][allowed_extensions]" value="<?php echo esc_attr($f['allowed_extensions']);?>"></label></p><p><label>最大ファイルサイズ（MB）<input type="number" min="1" name="nhk_form_fields[<?php echo esc_attr($i);?>][max_file_size_mb]" value="<?php echo esc_attr((int)$f['max_file_size_mb']);?>"></label></p></div>
 <p><label><input type="checkbox" name="nhk_form_fields[<?php echo esc_attr($i);?>][required]" value="1" <?php checked(!empty($f['required']));?>> 必須</label> <label><input type="checkbox" name="nhk_form_fields[<?php echo esc_attr($i);?>][row_end]" value="1" <?php checked(!empty($f['row_end']));?>> この項目の後で改行</label><button type="button" class="button nhk-up">上へ</button> <button type="button" class="button nhk-down">下へ</button> <button type="button" class="button-link-delete nhk-remove">削除</button></p></div><?php }
 public static function save($id,$post){
  if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(!isset($_POST[self::NONCE])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST[self::NONCE])),self::NONCE)||!current_user_can('edit_post',$id))return;
  $mode=sanitize_key(wp_unslash($_POST['nhk_form_mode']??'standard'));$schema=sanitize_key(wp_unslash($_POST['nhk_form_schema']??''));if(!in_array($mode,array('standard','post_submission'),true)||($mode==='post_submission'&&!NHK_Form_Schema_Registry::get($schema))){$mode='standard';$schema='';}
  update_post_meta($id,NHK_Form_Post_Type::META_MODE,$mode);update_post_meta($id,NHK_Form_Post_Type::META_SCHEMA,$schema);
  foreach(array('description'=>'META_DESCRIPTION','mail_subject'=>'META_MAIL_SUBJECT','success'=>'META_SUCCESS','from_name'=>'META_FROM_NAME') as $n=>$c)update_post_meta($id,constant('NHK_Form_Post_Type::'.$c),$n==='description'||$n==='success'?sanitize_textarea_field(wp_unslash($_POST['nhk_form_'.$n]??'')):sanitize_text_field(wp_unslash($_POST['nhk_form_'.$n]??'')));
  update_post_meta($id,NHK_Form_Post_Type::META_RECIPIENTS,sanitize_textarea_field(wp_unslash($_POST['nhk_form_recipients']??'')));$email=sanitize_email(wp_unslash($_POST['nhk_form_from_email']??''));update_post_meta($id,NHK_Form_Post_Type::META_FROM_EMAIL,is_email($email)?$email:'');
  $rm=sanitize_key(wp_unslash($_POST['nhk_form_reply_to_mode']??'none'));update_post_meta($id,NHK_Form_Post_Type::META_REPLY_TO_MODE,in_array($rm,array('none','fixed','form_field'),true)?$rm:'none');$re=sanitize_email(wp_unslash($_POST['nhk_form_reply_to_email']??''));update_post_meta($id,NHK_Form_Post_Type::META_REPLY_TO_EMAIL,is_email($re)?$re:'');update_post_meta($id,NHK_Form_Post_Type::META_REPLY_TO_FIELD,sanitize_key(wp_unslash($_POST['nhk_form_reply_to_field']??'')));update_post_meta($id,NHK_Form_Post_Type::META_AUTO_REPLY,isset($_POST['nhk_form_auto_reply'])?'1':'0');
  $rows=is_array($_POST['nhk_form_fields']??null)?wp_unslash($_POST['nhk_form_fields']):array();$fields=array();$used=array();$allowed=array('text','email','tel','number','date','textarea','select','radio','checkbox','file');foreach($rows as $r){$label=sanitize_text_field($r['label']??'');if(!$label)continue;$key=sanitize_key($r['key']??'');if(!$key)$key='field_'.(count($fields)+1);while(isset($used[$key]))$key.='_'.(count($fields)+1);$used[$key]=1;$type=in_array($r['type']??'', $allowed,true)?$r['type']:'text';$min=max(0,absint($r['min_length']??0));$max=max(0,absint($r['max_length']??0));if($max&&$max<$min)$max=$min;$width=(string)($r['width']??'100');if(!in_array($width,array('10','25','33','50','66','75','100'),true))$width='100';$fields[]=array('id'=>sanitize_key($r['id']??''),'key'=>$key,'label'=>$label,'type'=>$type,'required'=>!empty($r['required']),'help_text'=>sanitize_text_field($r['help_text']??''),'placeholder'=>sanitize_text_field($r['placeholder']??''),'options'=>sanitize_textarea_field($r['options']??''),'min_length'=>$min,'max_length'=>$max,'width'=>$width,'row_end'=>!empty($r['row_end']),'allowed_extensions'=>sanitize_text_field($r['allowed_extensions']??''),'max_file_size_mb'=>max(1,absint($r['max_file_size_mb']??5)));}update_post_meta($id,NHK_Form_Post_Type::META_FIELDS,$fields);
 }
}